# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files


- repo: https://github.com/thibaudcolas/pre-commit-stylelint
  rev: v14.12.0
  hooks:
    - id: stylelint
      args: [--report-needless-disables, --report-invalid-scope-disables]
